import z from "zod";
import { CredentialType, NodeType } from "@/generated/prisma";

const aiPlannerNodeTypes = [
  NodeType.MANUAL_TRIGGER,
  NodeType.SCHEDULE_TRIGGER,
  NodeType.IF,
  NodeType.WAIT,
  NodeType.SET,
  NodeType.MERGE,
  NodeType.LOOP_OVER_ITEMS,
  NodeType.CODE,
  NodeType.GOOGLE_FORM_TRIGGER,
  NodeType.STRIPE_TRIGGER,
  NodeType.HTTP_REQUEST,
  NodeType.GOOGLE_SHEETS,
  NodeType.EMAIL,
  NodeType.DISCORD,
  NodeType.SLACK,
  NodeType.TELEGRAM,
  NodeType.OPENAI,
  NodeType.GEMINI,
  NodeType.ANTHROPIC,
] as const;

export const aiBuilderModeSchema = z.enum([
  "generate",
  "regenerate",
  "improve",
  "optimize",
  "fix",
  "convert_manual",
]);

export const aiBuilderMessageSchema = z.object({
  role: z.enum(["user", "assistant", "system"]),
  content: z.string().min(1).max(4000),
});

export const aiWorkflowNodeSchema = z.object({
  id: z.string().min(1),
  type: z.enum(aiPlannerNodeTypes),
  title: z.string().min(1),
  description: z.string().optional(),
  data: z.record(z.string(), z.any()).default({}),
  position: z
    .object({
      x: z.number(),
      y: z.number(),
    })
    .optional(),
});

export const aiWorkflowConnectionSchema = z.object({
  from: z.string().min(1),
  to: z.string().min(1),
  fromOutput: z.string().default("source-1"),
  toInput: z.string().default("target-1"),
});

export const aiRequiredCredentialSchema = z.object({
  type: z.enum(CredentialType),
  displayName: z.string().min(1),
  nodeIds: z.array(z.string().min(1)).default([]),
  configured: z.boolean(),
  suggestedCredentialId: z.string().optional(),
  guidance: z.string().min(1),
});

export const aiMissingInputSchema = z.object({
  nodeId: z.string().min(1),
  field: z.string().min(1),
  question: z.string().min(1),
  whyItMatters: z.string().min(1),
  example: z.string().optional(),
});

export const aiWorkflowPlanSchema = z.object({
  workflowName: z.string().min(1),
  summary: z.string().min(1),
  explanation: z.string().min(1),
  nodes: z.array(aiWorkflowNodeSchema).min(1),
  connections: z.array(aiWorkflowConnectionSchema).default([]),
  requiredCredentials: z.array(aiRequiredCredentialSchema).default([]),
  missingInputs: z.array(aiMissingInputSchema).default([]),
  userNextSteps: z.array(z.string().min(1)).default([]),
  unsupportedRequests: z.array(z.string().min(1)).default([]),
  plannerNotes: z.array(z.string().min(1)).default([]),
});

export const aiWorkflowBuilderInputSchema = z.object({
  workflowId: z.string().min(1),
  prompt: z.string().min(1).max(4000),
  mode: aiBuilderModeSchema.default("generate"),
  history: z.array(aiBuilderMessageSchema).max(20).default([]),
  preferredProvider: z.enum(["openai", "gemini", "anthropic"]).optional(),
  currentNodes: z
    .array(
      z.object({
        id: z.string(),
        type: z.string().nullish(),
        data: z.record(z.string(), z.any()).optional(),
      }),
    )
    .default([]),
  currentEdges: z
    .array(
      z.object({
        source: z.string(),
        target: z.string(),
      }),
    )
    .default([]),
});

export const workflowAIMetadataSchema = z.object({
  generated: z.boolean(),
  prompt: z.string().min(1),
  provider: z.enum(["openai", "gemini", "anthropic"]),
  mode: aiBuilderModeSchema,
  messages: z.array(aiBuilderMessageSchema),
  plan: aiWorkflowPlanSchema.nullable(),
  summary: z.string().optional(),
  nextSteps: z.array(z.string()).optional(),
  requiredCredentials: z.array(z.any()).optional(),
  missingInputs: z.array(z.any()).optional(),
  unsupportedRequests: z.array(z.string()).optional(),
  plannerNotes: z.array(z.string()).optional(),
  hasManualEdits: z.boolean().default(false),
  autoGeneratedAt: z.string().datetime(),
  lastUpdatedAt: z.string().datetime(),
  version: z.literal(1),
});

export type AiBuilderMode = z.infer<typeof aiBuilderModeSchema>;
export type AiBuilderMessage = z.infer<typeof aiBuilderMessageSchema>;
export type AiWorkflowPlan = z.infer<typeof aiWorkflowPlanSchema>;
export type AiWorkflowBuilderInput = z.infer<
  typeof aiWorkflowBuilderInputSchema
>;
export type WorkflowAIMetadata = z.infer<typeof workflowAIMetadataSchema>;
