-- AlterEnum
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'BROWSER_SCRAPER';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'RESUME_CV';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'RANDOM_DELAY';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'LOGGER';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'ERROR_HANDLER';
